#!/bin/sh
7z e stackoverflow.com-Badges.7z
7z e stackoverflow.com-Comments.7z
7z e stackoverflow.com-PostHistory.7z
7z e stackoverflow.com-PostLinks.7z
#7z e stackoverflow.com-Posts.7z
7z e stackoverflow.com-Tags.7z
7z e stackoverflow.com-Users.7z
7z e stackoverflow.com-Votes.7z

